### PR TITLE
Added stdout logging to support bash piping

### PR DESCRIPTION
**Pull request by mkjaer**
I use your great script from inside a bash script and needed to pipe everything to a file so I added stream=sys.stdout to the logging config.
This is only the second time I change python scripts so bear with me.

### CODE REVIEW

**Comment by burnettk** [comment]
@mkjaer two things. one: i just fixed a bug with logging: 099a461. can you re-install and re-attempt whatever you are doing? second: logs go to stderr by default. can you use that instead of stdout? you may get what you want to redirecting stderr to the same stream with `2>&1`.

**Comment by mkjaer** [comment]
I tried the new version which seems to work if I pipe stderr into my logfile.

I guess I just didn't realize INFO statements also went into stderr. Is there a reason for that?

**Comment by burnettk** [comment]
technically speaking, all python logs seem to go to stderr by default ([reference](https://docs.python.org/2/library/logging.handlers.html)). i'm not entirely sure why they made that decision. shall we close this then?

**Comment by mkjaer** [comment]
I see. I guess it's mainly up to you how you want it to work. I got my script working so I don't mind either way :)

**Pull request closed without merging**
